// Generated by CoffeeScript 1.3.3
"use strict";

var app, express, routes;

express = require('express');

routes = require('./routes');

app = module.exports = express.createServer();

app.configure(function() {
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express["static"](__dirname + '/public'));
  return app.use(app.router);
});

app.configure('development', function() {
  app.set('cacheInSeconds', 0);
  app.set('port', 3333);
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  app.set('cacheInSeconds', 60 * 60);
  app.set('port', process.env.PORT || 5000);
  return app.use(express.errorHandler());
});

routes.init(app);

app.get('/', routes.index);

app.get('/about', routes.about);

app.get(/^\/talks\/?(\d{4})?\/?$/, routes.talks);

app.get('/praguejs.ics', routes.ical);

app.get('/*', routes.e404);

app.listen(app.settings.port);

console.log("Express server listening in " + app.settings.env + " mode at http://localhost:" + (app.address().port) + "/");
